site_name: Sergio Roa Portfolio
site_url: https://sergior-9605.github.io/projects-overview-sergio-roa/
theme:
  name: material
  language: en  # default languaje

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          # Esto es necesario para que Material for MkDocs sepa cómo renderizar el bloque 'mermaid'
          format: !!python/name:pymdownx.superfences.fence_code_format 

plugins:
  - search
  - i18n:
      docs_structure: suffix  # Esta es la clave
      languages:
        - locale: en
          name: English
          default: true
          build: true
        - locale: es
          name: Español
          build: true
          nav_translations:
            Home: Inicio
            Projects: Proyectos
            Overview: Resumen
            Experience: Experiencia
            Skills: Habilidades
            Education: Educación
            Contact: Contacto

nav:
  - Home: index.md
  - Projects:
      - Overview: projects/index.md
      - Luciana: projects/luciana.md
      # - Luciana front: projects/luciana-front.md
      - Payroll api: projects/payroll-api.md
      - Agroup: projects/agroup.md
  - Experience: experience.md
  - Skills: skills.md
  - Education: education.md
  - Contact: contact.md
